-- Product catalog seed (generated from live product pages)

insert into products (brand, name, slug, price, cod_advance) values ('Gymshark', 'Founder Edition Oversized Hoodie', 'gymshark-founder-hoodie', 5299, 4500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Gymshark', 'Lifting Essential Joggers', 'gymshark-lifting-essential-joggers', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Gymshark', 'Onyx 5.0 Seamless Compression Half Sleeve', 'gymshark-onyx-5-half-sleeve', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Gymshark', 'Onyx 5.0 Seamless Compression Full Sleeve', 'gymshark-onyx-5-long-sleeve', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Gymshark', 'Onyx 5.0 Seamless Compression Sleeveless', 'gymshark-onyx-5-sleeveless', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('YoungLA × Batman', 'Compression Half Sleeve', 'youngla-batman-half-sleeve', 4799, 4000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('YoungLA', 'Divine Sweats Sweatpants', 'youngla-divine-sweats', 4499, 2900) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('YoungLA', 'Drip Oversized T-Shirt', 'youngla-drip-oversized-tshirt', 4399, 2800) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('YoungLA × Gold''s Gym', 'Slim Fit T-Shirt', 'youngla-gold''s-gym-tshirt', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('YoungLA', 'Revenge Hoodie', 'youngla-revenge-hoodie', 5099, 3500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('YoungLA', 'Revenge Joggers', 'youngla-revenge-joggers', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('YoungLA × Superman', 'Compression Half Sleeve', 'youngla-superman-half-sleeve', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Blood Oath Sweatpants', 'breathedivinity-blood-oath-sweatpants', 5099, 3400) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Bloodraven Oversized T-Shirt', 'breathedivinity-bloodraven', 5299, 3600) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Deathclaw Oversized T-Shirt', 'breathedivinity-deathclaw', 5399, 3700) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Deathwing Oversized Hoodie', 'breathedivinity-deathwing-oversized-hoodie', 5299, 3500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Dragon Blade Oversized T-Shirt', 'breathedivinity-dragon-blade', 5399, 3700) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Eternal Wyvern Oversized Sweatpants', 'breathedivinity-eternal-wyvern-oversized-sweatpants', 5099, 3400) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Fallen Knight Long Sleeve Compression', 'breathedivinity-fallen-knight-long-sleeve', 5499, 3700) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Gargoyle Oversized T-Shirt', 'breathedivinity-gargoyle', 5399, 3700) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'Hollow Souls Oversized T-Shirt', 'breathedivinity-hollow-souls', 5299, 3500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'VoidTech Berserker Compression', 'breathedivinity-voidtech-berserker', 4799, 2500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'VoidTech Cyber Skeleton Compression', 'breathedivinity-voidtech-cyber-skeleton', 5299, 3500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'VoidTech Immortal Compression', 'breathedivinity-voidtech-immortal', 5299, 3500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'VoidTech Infernal Compression', 'breathedivinity-voidtech-infernal', 5299, 3500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'VoidTech Nightfall Compression Half Sleeve', 'breathedivinity-voidtech-nightfall-half-sleeve', 4299, 2500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('BreatheDivinity', 'VoidTech PulseFire Compression', 'breathedivinity-voidtech-pulsefire', 5299, 3500) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Chrome Hearts', 'Forever Black Denim Jacket', 'chromehearts-forever-denim-jacket', 8999, 7300) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Chrome Hearts × Mastermind', 'Ripped Denim Jacket', 'chromehearts-mastermind-ripped-denim-jacket', 8999, 7300) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Chrome Hearts', 'Retro Hoodie', 'chromehearts-retro-hoodie', 4799, 5100) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Chrome Hearts', 'Retro Jeans', 'chromehearts-retro-jeans', 7499, 5600) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Chrome Hearts', 'Retro Oversized T-Shirt', 'chromehearts-retro-oversized-tshirt', 4799, 3100) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Chrome Hearts', 'Vintage Oversized T-Shirt', 'chromehearts-vintage-oversized-tshirt', 4799, 3100) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Cactus Jack x Travis Scott', 'Astroworld Oversized T-Shirt', 'cactusjack-astroworld-oversized-tshirt', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Cactus Jack x Travis Scott x Fragment', 'Oversized T-Shirt', 'cactusjack-fragment-oversized-tshirt', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Cactus Jack x Travis Scott x McDonald''s', 'Oversized T-Shirt', 'cactusjack-mcdonalds-oversized-tshirt', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Cactus Jack x Travis Scott', 'Oversized T-Shirt', 'cactusjack-oversized-tshirt', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Cactus Jack x Travis Scott x Playstation', 'Oversized T-Shirt', 'cactusjack-playstation-oversized-tshirt', 4799, 3000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Skims', 'Cotton Jersey T-Shirt', 'skims-cotton-jersey-tshirt', 4399, 2600) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Skims', 'Rhinestone Logo Pointelle Mini Slip Dress', 'skims-rhinestone-logo-mini-dress', 6499, 4900) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;
insert into products (brand, name, slug, price, cod_advance) values ('Lululemon', 'Define Nulu Jacket + Align Yoga Pants Set', 'lululemon-define-nulu-align-yoga-set', 6499, 6000) on conflict (slug) do update set brand=excluded.brand, name=excluded.name, price=excluded.price, cod_advance=excluded.cod_advance;

-- Product colors (linked by slug lookup; re-runnable without duplicating rows)

delete from product_colors where product_id in (select id from products);
insert into product_colors (product_id, label, hex, image_index) select id, 'Forest Green', '#1a4a35', 0 from products where slug = 'gymshark-founder-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#1a1a1a', 2 from products where slug = 'gymshark-founder-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#c41e1e', 0 from products where slug = 'gymshark-lifting-essential-joggers';
insert into product_colors (product_id, label, hex, image_index) select id, 'Stealth Black', '#0d0d0d', 3 from products where slug = 'gymshark-lifting-essential-joggers';
insert into product_colors (product_id, label, hex, image_index) select id, 'Navy', '#2c3244', 6 from products where slug = 'gymshark-lifting-essential-joggers';
insert into product_colors (product_id, label, hex, image_index) select id, 'Grey', '#9a9a9a', 9 from products where slug = 'gymshark-lifting-essential-joggers';
insert into product_colors (product_id, label, hex, image_index) select id, 'Forest Green', '#1a4a1a', 0 from products where slug = 'gymshark-onyx-5-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Deep Purple', '#3a1a5a', 2 from products where slug = 'gymshark-onyx-5-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Stealth Black', '#1a1a1a', 4 from products where slug = 'gymshark-onyx-5-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Dark Red', '#5a1a1a', 6 from products where slug = 'gymshark-onyx-5-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#1a1a1a', 0 from products where slug = 'gymshark-onyx-5-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Dark Red', '#5a1a1a', 2 from products where slug = 'gymshark-onyx-5-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Teal', '#1a4a4a', 4 from products where slug = 'gymshark-onyx-5-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Gray', '#4a4a4a', 6 from products where slug = 'gymshark-onyx-5-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#1a1a1a', 0 from products where slug = 'gymshark-onyx-5-sleeveless';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#3a1a5a', 2 from products where slug = 'gymshark-onyx-5-sleeveless';
insert into product_colors (product_id, label, hex, image_index) select id, 'Dark Red', '#5a1a1a', 4 from products where slug = 'gymshark-onyx-5-sleeveless';
insert into product_colors (product_id, label, hex, image_index) select id, 'Dark Knight', '#1a1a2e', 0 from products where slug = 'youngla-batman-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Stealth', '#2a2a2a', 2 from products where slug = 'youngla-batman-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#e8e8e8', 3 from products where slug = 'youngla-batman-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Maroon', '#5a2a35', 0 from products where slug = 'youngla-divine-sweats';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 1 from products where slug = 'youngla-divine-sweats';
insert into product_colors (product_id, label, hex, image_index) select id, 'Navy', '#2e3240', 2 from products where slug = 'youngla-divine-sweats';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#3f2f4a', 3 from products where slug = 'youngla-divine-sweats';
insert into product_colors (product_id, label, hex, image_index) select id, 'Charcoal', '#3a3d3a', 5 from products where slug = 'youngla-divine-sweats';
insert into product_colors (product_id, label, hex, image_index) select id, 'Maroon', '#5a2a35', 0 from products where slug = 'youngla-drip-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Brown', '#4a3f30', 3 from products where slug = 'youngla-drip-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 6 from products where slug = 'youngla-drip-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Maroon', '#6e1f2a', 0 from products where slug = 'youngla-gold''s-gym-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 1 from products where slug = 'youngla-gold''s-gym-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Yellow', '#f2c318', 3 from products where slug = 'youngla-gold''s-gym-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Cream', '#ece7db', 4 from products where slug = 'youngla-gold''s-gym-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Green', '#0d3b2e', 0 from products where slug = 'youngla-revenge-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Grey', '#8a8a8a', 2 from products where slug = 'youngla-revenge-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 3 from products where slug = 'youngla-revenge-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#413a52', 0 from products where slug = 'youngla-revenge-joggers';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 2 from products where slug = 'youngla-revenge-joggers';
insert into product_colors (product_id, label, hex, image_index) select id, 'Teal', '#0e5f5f', 4 from products where slug = 'youngla-revenge-joggers';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#c41e1e', 7 from products where slug = 'youngla-revenge-joggers';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#12141c', 0 from products where slug = 'youngla-superman-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#c41e1e', 1 from products where slug = 'youngla-superman-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#1e3fc4', 2 from products where slug = 'youngla-superman-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 1 from products where slug = 'breathedivinity-blood-oath-sweatpants';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 3 from products where slug = 'breathedivinity-blood-oath-sweatpants';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 7 from products where slug = 'breathedivinity-blood-oath-sweatpants';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 2 from products where slug = 'breathedivinity-bloodraven';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 4 from products where slug = 'breathedivinity-bloodraven';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 0 from products where slug = 'breathedivinity-bloodraven';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red White', '#8a1c1c', 6 from products where slug = 'breathedivinity-bloodraven';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#1c4aa0', 8 from products where slug = 'breathedivinity-bloodraven';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 10 from products where slug = 'breathedivinity-bloodraven';
insert into product_colors (product_id, label, hex, image_index) select id, 'Pink', '#c41e8a', 12 from products where slug = 'breathedivinity-bloodraven';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red White', '#8a1c1c', 0 from products where slug = 'breathedivinity-deathclaw';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 2 from products where slug = 'breathedivinity-deathclaw';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 0 from products where slug = 'breathedivinity-deathwing-oversized-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 2 from products where slug = 'breathedivinity-deathwing-oversized-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 4 from products where slug = 'breathedivinity-deathwing-oversized-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#1c4aa0', 0 from products where slug = 'breathedivinity-dragon-blade';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 2 from products where slug = 'breathedivinity-dragon-blade';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 4 from products where slug = 'breathedivinity-dragon-blade';
insert into product_colors (product_id, label, hex, image_index) select id, 'Orange', '#c46a1e', 6 from products where slug = 'breathedivinity-dragon-blade';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 8 from products where slug = 'breathedivinity-dragon-blade';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red Blue', '#7a2c4a', 10 from products where slug = 'breathedivinity-dragon-blade';
insert into product_colors (product_id, label, hex, image_index) select id, 'Pink', '#c41e8a', 12 from products where slug = 'breathedivinity-dragon-blade';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 0 from products where slug = 'breathedivinity-eternal-wyvern-oversized-sweatpants';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 1 from products where slug = 'breathedivinity-eternal-wyvern-oversized-sweatpants';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 4 from products where slug = 'breathedivinity-eternal-wyvern-oversized-sweatpants';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 7 from products where slug = 'breathedivinity-eternal-wyvern-oversized-sweatpants';
insert into product_colors (product_id, label, hex, image_index) select id, 'Orange', '#c46a1e', 0 from products where slug = 'breathedivinity-fallen-knight-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Pink', '#c41e8a', 2 from products where slug = 'breathedivinity-fallen-knight-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#1c4aa0', 4 from products where slug = 'breathedivinity-fallen-knight-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 6 from products where slug = 'breathedivinity-fallen-knight-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 8 from products where slug = 'breathedivinity-fallen-knight-long-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 0 from products where slug = 'breathedivinity-gargoyle';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 2 from products where slug = 'breathedivinity-gargoyle';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 4 from products where slug = 'breathedivinity-gargoyle';
insert into product_colors (product_id, label, hex, image_index) select id, 'Crimson', '#8a1c1c', 6 from products where slug = 'breathedivinity-gargoyle';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 0 from products where slug = 'breathedivinity-hollow-souls';
insert into product_colors (product_id, label, hex, image_index) select id, 'Charcoal', '#3a3a3a', 2 from products where slug = 'breathedivinity-hollow-souls';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#1c4aa0', 4 from products where slug = 'breathedivinity-hollow-souls';
insert into product_colors (product_id, label, hex, image_index) select id, 'Green', '#1c8a3a', 5 from products where slug = 'breathedivinity-hollow-souls';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 7 from products where slug = 'breathedivinity-hollow-souls';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 9 from products where slug = 'breathedivinity-hollow-souls';
insert into product_colors (product_id, label, hex, image_index) select id, 'Orange', '#c46a1e', 10 from products where slug = 'breathedivinity-hollow-souls';
insert into product_colors (product_id, label, hex, image_index) select id, 'Pink', '#c41e8a', 11 from products where slug = 'breathedivinity-hollow-souls';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 0 from products where slug = 'breathedivinity-voidtech-berserker';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 2 from products where slug = 'breathedivinity-voidtech-berserker';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 4 from products where slug = 'breathedivinity-voidtech-berserker';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#1c4aa0', 6 from products where slug = 'breathedivinity-voidtech-berserker';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 0 from products where slug = 'breathedivinity-voidtech-cyber-skeleton';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 2 from products where slug = 'breathedivinity-voidtech-cyber-skeleton';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 0 from products where slug = 'breathedivinity-voidtech-immortal';
insert into product_colors (product_id, label, hex, image_index) select id, 'White Red', '#8a1c1c', 2 from products where slug = 'breathedivinity-voidtech-immortal';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 4 from products where slug = 'breathedivinity-voidtech-immortal';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 6 from products where slug = 'breathedivinity-voidtech-immortal';
insert into product_colors (product_id, label, hex, image_index) select id, 'Green', '#1c8a3a', 8 from products where slug = 'breathedivinity-voidtech-immortal';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 0 from products where slug = 'breathedivinity-voidtech-infernal';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 2 from products where slug = 'breathedivinity-voidtech-infernal';
insert into product_colors (product_id, label, hex, image_index) select id, 'Red', '#a01c1c', 4 from products where slug = 'breathedivinity-voidtech-infernal';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#1c4aa0', 6 from products where slug = 'breathedivinity-voidtech-infernal';
insert into product_colors (product_id, label, hex, image_index) select id, 'Pink', '#c41e8a', 9 from products where slug = 'breathedivinity-voidtech-infernal';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#1a1a1a', 0 from products where slug = 'breathedivinity-voidtech-nightfall-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Crimson Red', '#5a1a1a', 1 from products where slug = 'breathedivinity-voidtech-nightfall-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'Gold', '#8a5a00', 2 from products where slug = 'breathedivinity-voidtech-nightfall-half-sleeve';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#3a3a3a', 0 from products where slug = 'breathedivinity-voidtech-pulsefire';
insert into product_colors (product_id, label, hex, image_index) select id, 'PulseFire', '#a01c5a', 1 from products where slug = 'breathedivinity-voidtech-pulsefire';
insert into product_colors (product_id, label, hex, image_index) select id, 'Purple', '#5a1ca0', 2 from products where slug = 'breathedivinity-voidtech-pulsefire';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#1c4aa0', 3 from products where slug = 'breathedivinity-voidtech-pulsefire';
insert into product_colors (product_id, label, hex, image_index) select id, 'Orange', '#c46a1e', 4 from products where slug = 'breathedivinity-voidtech-pulsefire';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 0 from products where slug = 'chromehearts-forever-denim-jacket';
insert into product_colors (product_id, label, hex, image_index) select id, 'Denim Blue', '#6b9fd4', 0 from products where slug = 'chromehearts-mastermind-ripped-denim-jacket';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 2 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 4 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 4', '#2a2a2a', 6 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 5', '#2a2a2a', 8 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 6', '#2a2a2a', 10 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 7', '#2a2a2a', 12 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 8', '#2a2a2a', 14 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 9', '#2a2a2a', 16 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 10', '#2a2a2a', 18 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 11', '#2a2a2a', 20 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 12', '#2a2a2a', 22 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 13', '#2a2a2a', 24 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 14', '#2a2a2a', 26 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 15', '#2a2a2a', 28 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 16', '#2a2a2a', 30 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 17', '#2a2a2a', 32 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 18', '#2a2a2a', 34 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 19', '#2a2a2a', 36 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 20', '#2a2a2a', 38 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 21', '#2a2a2a', 40 from products where slug = 'chromehearts-retro-hoodie';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'chromehearts-retro-jeans';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 1 from products where slug = 'chromehearts-retro-jeans';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 2 from products where slug = 'chromehearts-retro-jeans';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 4', '#2a2a2a', 3 from products where slug = 'chromehearts-retro-jeans';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 5', '#2a2a2a', 4 from products where slug = 'chromehearts-retro-jeans';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 6', '#2a2a2a', 5 from products where slug = 'chromehearts-retro-jeans';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 1 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 2 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 4', '#2a2a2a', 4 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 5', '#2a2a2a', 6 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 6', '#2a2a2a', 8 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 7', '#2a2a2a', 10 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 8', '#2a2a2a', 12 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 9', '#2a2a2a', 14 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 10', '#2a2a2a', 16 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 11', '#2a2a2a', 18 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 12', '#2a2a2a', 20 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 13', '#2a2a2a', 22 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 14', '#2a2a2a', 24 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 15', '#2a2a2a', 26 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 16', '#2a2a2a', 28 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 17', '#2a2a2a', 30 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 18', '#2a2a2a', 32 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 19', '#2a2a2a', 34 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 20', '#2a2a2a', 36 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 21', '#2a2a2a', 38 from products where slug = 'chromehearts-retro-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 1 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 2 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 4', '#2a2a2a', 3 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 5', '#2a2a2a', 4 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 6', '#2a2a2a', 5 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 7', '#2a2a2a', 6 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 8', '#2a2a2a', 7 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 9', '#2a2a2a', 8 from products where slug = 'chromehearts-vintage-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 1 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 2 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 4', '#2a2a2a', 3 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 5', '#2a2a2a', 4 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 6', '#2a2a2a', 5 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 7', '#2a2a2a', 6 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 8', '#2a2a2a', 7 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 9', '#2a2a2a', 8 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 10', '#2a2a2a', 9 from products where slug = 'cactusjack-astroworld-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'cactusjack-fragment-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 1 from products where slug = 'cactusjack-fragment-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 2 from products where slug = 'cactusjack-fragment-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 4', '#2a2a2a', 3 from products where slug = 'cactusjack-fragment-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 5', '#2a2a2a', 4 from products where slug = 'cactusjack-fragment-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 6', '#2a2a2a', 5 from products where slug = 'cactusjack-fragment-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 1 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 2 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 4', '#2a2a2a', 3 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 5', '#2a2a2a', 4 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 6', '#2a2a2a', 5 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 7', '#2a2a2a', 6 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 8', '#2a2a2a', 7 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 9', '#2a2a2a', 8 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 10', '#2a2a2a', 9 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 11', '#2a2a2a', 10 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 12', '#2a2a2a', 11 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 13', '#2a2a2a', 12 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 14', '#2a2a2a', 13 from products where slug = 'cactusjack-mcdonalds-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'cactusjack-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 1 from products where slug = 'cactusjack-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 2 from products where slug = 'cactusjack-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 4', '#2a2a2a', 3 from products where slug = 'cactusjack-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 5', '#2a2a2a', 4 from products where slug = 'cactusjack-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 6', '#2a2a2a', 5 from products where slug = 'cactusjack-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 7', '#2a2a2a', 6 from products where slug = 'cactusjack-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 8', '#2a2a2a', 7 from products where slug = 'cactusjack-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 1', '#2a2a2a', 0 from products where slug = 'cactusjack-playstation-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 2', '#2a2a2a', 1 from products where slug = 'cactusjack-playstation-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Variant 3', '#2a2a2a', 2 from products where slug = 'cactusjack-playstation-oversized-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Heather Grey', '#c9c9c9', 0 from products where slug = 'skims-cotton-jersey-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 3 from products where slug = 'skims-cotton-jersey-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#f0ede8', 6 from products where slug = 'skims-cotton-jersey-tshirt';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 0 from products where slug = 'skims-rhinestone-logo-mini-dress';
insert into product_colors (product_id, label, hex, image_index) select id, 'Pink', '#e8a8cf', 2 from products where slug = 'skims-rhinestone-logo-mini-dress';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#f0ede8', 4 from products where slug = 'skims-rhinestone-logo-mini-dress';
insert into product_colors (product_id, label, hex, image_index) select id, 'Blue', '#a8bcc8', 0 from products where slug = 'lululemon-define-nulu-align-yoga-set';
insert into product_colors (product_id, label, hex, image_index) select id, 'Mauve', '#c9a898', 2 from products where slug = 'lululemon-define-nulu-align-yoga-set';
insert into product_colors (product_id, label, hex, image_index) select id, 'Black', '#141414', 4 from products where slug = 'lululemon-define-nulu-align-yoga-set';
insert into product_colors (product_id, label, hex, image_index) select id, 'White', '#f0ede8', 6 from products where slug = 'lululemon-define-nulu-align-yoga-set';
